from collections.abc import Awaitable, Callable, Sequence

__version__: str

class Chunk:
    @property
    def text(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def hash(self) -> str: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class EmbeddingError(Exception): ...

class NaiveChunker:
    def __init__(self, chunk_size: int = 200) -> None: ...
    def chunk(self, text: str) -> list[Chunk]: ...
    def chunk_many(self, texts: Sequence[str]) -> list[list[Chunk]]: ...
    async def chunk_async(self, text: str) -> list[Chunk]: ...
    async def chunk_many_async(self, texts: Sequence[str]) -> list[list[Chunk]]: ...

class FixedSizeChunker:
    def __init__(
        self,
        chunk_size: int = 1000,
        chunk_overlap: int = 200,
        respect_sentences: bool = True,
    ) -> None: ...
    def chunk(self, text: str) -> list[Chunk]: ...
    def chunk_many(self, texts: Sequence[str]) -> list[list[Chunk]]: ...
    async def chunk_async(self, text: str) -> list[Chunk]: ...
    async def chunk_many_async(self, texts: Sequence[str]) -> list[list[Chunk]]: ...

class RecursiveChunker:
    def __init__(
        self,
        chunk_size: int = 1000,
        chunk_overlap: int = 200,
        separators: list[str] | None = None,
    ) -> None: ...
    def chunk(self, text: str) -> list[Chunk]: ...
    def chunk_many(self, texts: Sequence[str]) -> list[list[Chunk]]: ...
    async def chunk_async(self, text: str) -> list[Chunk]: ...
    async def chunk_many_async(self, texts: Sequence[str]) -> list[list[Chunk]]: ...

class SentenceChunker:
    def __init__(self, max_chars: int = 1000, overlap_sentences: int = 1) -> None: ...
    def chunk(self, text: str) -> list[Chunk]: ...
    def chunk_many(self, texts: Sequence[str]) -> list[list[Chunk]]: ...
    async def chunk_async(self, text: str) -> list[Chunk]: ...
    async def chunk_many_async(self, texts: Sequence[str]) -> list[list[Chunk]]: ...

class MarkdownChunker:
    def __init__(self, chunk_size: int = 1000, chunk_overlap: int = 200) -> None: ...
    def chunk(self, text: str) -> list[Chunk]: ...
    def chunk_many(self, texts: Sequence[str]) -> list[list[Chunk]]: ...
    async def chunk_async(self, text: str) -> list[Chunk]: ...
    async def chunk_many_async(self, texts: Sequence[str]) -> list[list[Chunk]]: ...

class TokenChunker:
    def __init__(
        self,
        chunk_size: int = 512,
        chunk_overlap: int = 64,
        encoding: str = "cl100k_base",
    ) -> None: ...
    def chunk(self, text: str) -> list[Chunk]: ...
    def chunk_many(self, texts: Sequence[str]) -> list[list[Chunk]]: ...
    async def chunk_async(self, text: str) -> list[Chunk]: ...
    async def chunk_many_async(self, texts: Sequence[str]) -> list[list[Chunk]]: ...

class OpenAIEmbedder:
    def __init__(
        self,
        base_url: str,
        model: str,
        api_key: str | None = None,
        batch_size: int = 128,
    ) -> None: ...
    async def embed_async(self, texts: Sequence[str]) -> list[list[float]]: ...

EmbedderLike = OpenAIEmbedder | Callable[[list[str]], Awaitable[list[list[float]]]]

class SemanticChunker:
    def __init__(
        self,
        embedder: EmbedderLike,
        threshold: float | None = None,
        percentile: float = 95.0,
        min_chunk_size: int = 0,
        max_chunk_size: int | None = None,
    ) -> None: ...
    def chunk(self, text: str) -> list[Chunk]: ...
    def chunk_many(self, texts: Sequence[str]) -> list[list[Chunk]]: ...
    async def chunk_async(self, text: str) -> list[Chunk]: ...
    async def chunk_many_async(self, texts: Sequence[str]) -> list[list[Chunk]]: ...
